//! NOTE: this source file is autogenerated, DO NOT MODIFY

//
// constants
//

//
// types
//
// --------------------------------------------------------
// Type: LPMAPILOGON
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPILOGON = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPILOGOFF
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPILOGOFF = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPISENDMAIL
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPISENDMAIL = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPISENDMAILW
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPISENDMAILW = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPISENDDOCUMENTS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPISENDDOCUMENTS = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPIFINDNEXT
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPIFINDNEXT = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPIREADMAIL
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPIREADMAIL = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPISAVEMAIL
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPISAVEMAIL = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPIDELETEMAIL
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPIDELETEMAIL = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPIFREEBUFFER
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPIFREEBUFFER = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPIADDRESS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPIADDRESS = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPIDETAILS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPIDETAILS = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: LPMAPIRESOLVENAME
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const LPMAPIRESOLVENAME = *opaque{
    // TODO: Method '.ctor'
    // TODO: Method 'Invoke'
};
// --------------------------------------------------------
// Type: MBN_SIGNAL_CONSTANTS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_SIGNAL_CONSTANTS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_CELLULAR_CLASS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_CELLULAR_CLASS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_VOICE_CLASS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_VOICE_CLASS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_PROVIDER_STATE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_PROVIDER_STATE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_PROVIDER_CONSTANTS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_PROVIDER_CONSTANTS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_INTERFACE_CAPS_CONSTANTS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_INTERFACE_CAPS_CONSTANTS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_DATA_CLASS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_DATA_CLASS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_CTRL_CAPS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_CTRL_CAPS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_SMS_CAPS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_SMS_CAPS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_BAND_CLASS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_BAND_CLASS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_INTERFACE_CAPS
// TypeLayoutAttr: sequential
// TODO: I think this is a struct, but not sure at this point, assuming it is for now
pub const MBN_INTERFACE_CAPS = extern struct {
    cellularClass: MBN_CELLULAR_CLASS,
    voiceClass: MBN_VOICE_CLASS,
    dataClass: u32,
    customDataClass: BSTR,
    gsmBandClass: u32,
    cdmaBandClass: u32,
    customBandClass: BSTR,
    smsCaps: u32,
    controlCaps: u32,
    deviceID: BSTR,
    manufacturer: BSTR,
    model: BSTR,
    firmwareInfo: BSTR,
};
// --------------------------------------------------------
// Type: MBN_PROVIDER
// TypeLayoutAttr: sequential
// TODO: I think this is a struct, but not sure at this point, assuming it is for now
pub const MBN_PROVIDER = extern struct {
    providerID: BSTR,
    providerState: u32,
    providerName: BSTR,
    dataClass: u32,
};
// --------------------------------------------------------
// Type: MBN_PROVIDER2
// TypeLayoutAttr: sequential
// TODO: I think this is a struct, but not sure at this point, assuming it is for now
pub const MBN_PROVIDER2 = extern struct {
    provider: MBN_PROVIDER,
    cellularClass: MBN_CELLULAR_CLASS,
    signalStrength: u32,
    signalError: u32,
};
// --------------------------------------------------------
// Type: MBN_READY_STATE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_READY_STATE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_ACTIVATION_STATE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_ACTIVATION_STATE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_CONNECTION_MODE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_CONNECTION_MODE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_VOICE_CALL_STATE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_VOICE_CALL_STATE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_REGISTRATION_CONSTANTS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_REGISTRATION_CONSTANTS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_REGISTER_STATE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_REGISTER_STATE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_REGISTER_MODE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_REGISTER_MODE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_PIN_CONSTANTS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_PIN_CONSTANTS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_PIN_STATE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_PIN_STATE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_PIN_TYPE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_PIN_TYPE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_PIN_INFO
// TypeLayoutAttr: sequential
// TODO: I think this is a struct, but not sure at this point, assuming it is for now
pub const MBN_PIN_INFO = extern struct {
    pinState: MBN_PIN_STATE,
    pinType: MBN_PIN_TYPE,
    attemptsRemaining: u32,
};
// --------------------------------------------------------
// Type: MBN_PIN_MODE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_PIN_MODE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_PIN_FORMAT
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_PIN_FORMAT = *opaque{
};
// --------------------------------------------------------
// Type: MBN_CONTEXT_CONSTANTS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_CONTEXT_CONSTANTS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_AUTH_PROTOCOL
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_AUTH_PROTOCOL = *opaque{
};
// --------------------------------------------------------
// Type: MBN_COMPRESSION
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_COMPRESSION = *opaque{
};
// --------------------------------------------------------
// Type: MBN_CONTEXT_TYPE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_CONTEXT_TYPE = *opaque{
};
// --------------------------------------------------------
// Type: MBN_CONTEXT
// TypeLayoutAttr: sequential
// TODO: I think this is a struct, but not sure at this point, assuming it is for now
pub const MBN_CONTEXT = extern struct {
    contextID: u32,
    contextType: MBN_CONTEXT_TYPE,
    accessString: BSTR,
    userName: BSTR,
    password: BSTR,
    compression: MBN_COMPRESSION,
    authType: MBN_AUTH_PROTOCOL,
};
// --------------------------------------------------------
// Type: WWAEXT_SMS_CONSTANTS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const WWAEXT_SMS_CONSTANTS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_MSG_STATUS
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_MSG_STATUS = *opaque{
};
// --------------------------------------------------------
// Type: MBN_SMS_CDMA_LANG
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_SMS_CDMA_LANG = *opaque{
};
// --------------------------------------------------------
// Type: MBN_SMS_CDMA_ENCODING
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_SMS_CDMA_ENCODING = *opaque{
};
// --------------------------------------------------------
// Type: MBN_SMS_FLAG
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_SMS_FLAG = *opaque{
};
// --------------------------------------------------------
// Type: MBN_SMS_FILTER
// TypeLayoutAttr: sequential
// TODO: I think this is a struct, but not sure at this point, assuming it is for now
pub const MBN_SMS_FILTER = extern struct {
    flag: MBN_SMS_FLAG,
    messageIndex: u32,
};
// --------------------------------------------------------
// Type: MBN_SMS_STATUS_FLAG
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_SMS_STATUS_FLAG = *opaque{
};
// --------------------------------------------------------
// Type: MBN_SMS_STATUS_INFO
// TypeLayoutAttr: sequential
// TODO: I think this is a struct, but not sure at this point, assuming it is for now
pub const MBN_SMS_STATUS_INFO = extern struct {
    flag: u32,
    messageIndex: u32,
};
// --------------------------------------------------------
// Type: MBN_SMS_FORMAT
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_SMS_FORMAT = *opaque{
};
// --------------------------------------------------------
// Type: MBN_RADIO
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_RADIO = *opaque{
};
// --------------------------------------------------------
// Type: MBN_DEVICE_SERVICE
// TypeLayoutAttr: sequential
// TODO: I think this is a struct, but not sure at this point, assuming it is for now
pub const MBN_DEVICE_SERVICE = extern struct {
    deviceServiceID: BSTR,
    dataWriteSupported: i16,
    dataReadSupported: i16,
};
// --------------------------------------------------------
// Type: MBN_DEVICE_SERVICES_INTERFACE_STATE
// TypeLayoutAttr: auto
// not generating the actual code for this type because it has an 'auto' layout (follow up on https://github.com/microsoft/win32metadata/issues/188)
pub const MBN_DEVICE_SERVICES_INTERFACE_STATE = *opaque{
};
// --------------------------------------------------------
// Type: IMbnConnection
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnection = *opaque{
    // TODO: Method 'get_ConnectionID'
    // TODO: Method 'get_InterfaceID'
    // TODO: Method 'Connect'
    // TODO: Method 'Disconnect'
    // TODO: Method 'GetConnectionState'
    // TODO: Method 'GetVoiceCallState'
    // TODO: Method 'GetActivationNetworkError'
};
// --------------------------------------------------------
// Type: IMbnConnectionEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnectionEvents = *opaque{
    // TODO: Method 'OnConnectComplete'
    // TODO: Method 'OnDisconnectComplete'
    // TODO: Method 'OnConnectStateChange'
    // TODO: Method 'OnVoiceCallStateChange'
};
// --------------------------------------------------------
// Type: IMbnInterface
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnInterface = *opaque{
    // TODO: Method 'get_InterfaceID'
    // TODO: Method 'GetInterfaceCapability'
    // TODO: Method 'GetSubscriberInformation'
    // TODO: Method 'GetReadyState'
    // TODO: Method 'InEmergencyMode'
    // TODO: Method 'GetHomeProvider'
    // TODO: Method 'GetPreferredProviders'
    // TODO: Method 'SetPreferredProviders'
    // TODO: Method 'GetVisibleProviders'
    // TODO: Method 'ScanNetwork'
    // TODO: Method 'GetConnection'
};
// --------------------------------------------------------
// Type: IMbnInterfaceEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnInterfaceEvents = *opaque{
    // TODO: Method 'OnInterfaceCapabilityAvailable'
    // TODO: Method 'OnSubscriberInformationChange'
    // TODO: Method 'OnReadyStateChange'
    // TODO: Method 'OnEmergencyModeChange'
    // TODO: Method 'OnHomeProviderAvailable'
    // TODO: Method 'OnPreferredProvidersChange'
    // TODO: Method 'OnSetPreferredProvidersComplete'
    // TODO: Method 'OnScanNetworkComplete'
};
// --------------------------------------------------------
// Type: IMbnInterfaceManager
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnInterfaceManager = *opaque{
    // TODO: Method 'GetInterface'
    // TODO: Method 'GetInterfaces'
};
// --------------------------------------------------------
// Type: IMbnInterfaceManagerEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnInterfaceManagerEvents = *opaque{
    // TODO: Method 'OnInterfaceArrival'
    // TODO: Method 'OnInterfaceRemoval'
};
// --------------------------------------------------------
// Type: IMbnRegistration
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnRegistration = *opaque{
    // TODO: Method 'GetRegisterState'
    // TODO: Method 'GetRegisterMode'
    // TODO: Method 'GetProviderID'
    // TODO: Method 'GetProviderName'
    // TODO: Method 'GetRoamingText'
    // TODO: Method 'GetAvailableDataClasses'
    // TODO: Method 'GetCurrentDataClass'
    // TODO: Method 'GetRegistrationNetworkError'
    // TODO: Method 'GetPacketAttachNetworkError'
    // TODO: Method 'SetRegisterMode'
};
// --------------------------------------------------------
// Type: IMbnRegistrationEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnRegistrationEvents = *opaque{
    // TODO: Method 'OnRegisterModeAvailable'
    // TODO: Method 'OnRegisterStateChange'
    // TODO: Method 'OnPacketServiceStateChange'
    // TODO: Method 'OnSetRegisterModeComplete'
};
// --------------------------------------------------------
// Type: IMbnConnectionManager
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnectionManager = *opaque{
    // TODO: Method 'GetConnection'
    // TODO: Method 'GetConnections'
};
// --------------------------------------------------------
// Type: IMbnConnectionManagerEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnectionManagerEvents = *opaque{
    // TODO: Method 'OnConnectionArrival'
    // TODO: Method 'OnConnectionRemoval'
};
// --------------------------------------------------------
// Type: IMbnPinManager
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnPinManager = *opaque{
    // TODO: Method 'GetPinList'
    // TODO: Method 'GetPin'
    // TODO: Method 'GetPinState'
};
// --------------------------------------------------------
// Type: IMbnPinManagerEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnPinManagerEvents = *opaque{
    // TODO: Method 'OnPinListAvailable'
    // TODO: Method 'OnGetPinStateComplete'
};
// --------------------------------------------------------
// Type: IMbnPinEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnPinEvents = *opaque{
    // TODO: Method 'OnEnableComplete'
    // TODO: Method 'OnDisableComplete'
    // TODO: Method 'OnEnterComplete'
    // TODO: Method 'OnChangeComplete'
    // TODO: Method 'OnUnblockComplete'
};
// --------------------------------------------------------
// Type: IMbnSubscriberInformation
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnSubscriberInformation = *opaque{
    // TODO: Method 'get_SubscriberID'
    // TODO: Method 'get_SimIccID'
    // TODO: Method 'get_TelephoneNumbers'
};
// --------------------------------------------------------
// Type: IMbnSignal
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnSignal = *opaque{
    // TODO: Method 'GetSignalStrength'
    // TODO: Method 'GetSignalError'
};
// --------------------------------------------------------
// Type: IMbnSignalEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnSignalEvents = *opaque{
    // TODO: Method 'OnSignalStateChange'
};
// --------------------------------------------------------
// Type: IMbnConnectionContext
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnectionContext = *opaque{
    // TODO: Method 'GetProvisionedContexts'
    // TODO: Method 'SetProvisionedContext'
};
// --------------------------------------------------------
// Type: IMbnConnectionContextEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnectionContextEvents = *opaque{
    // TODO: Method 'OnProvisionedContextListChange'
    // TODO: Method 'OnSetProvisionedContextComplete'
};
// --------------------------------------------------------
// Type: IMbnConnectionProfileManager
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnectionProfileManager = *opaque{
    // TODO: Method 'GetConnectionProfiles'
    // TODO: Method 'GetConnectionProfile'
    // TODO: Method 'CreateConnectionProfile'
};
// --------------------------------------------------------
// Type: IMbnConnectionProfile
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnectionProfile = *opaque{
    // TODO: Method 'GetProfileXmlData'
    // TODO: Method 'UpdateProfile'
    // TODO: Method 'Delete'
};
// --------------------------------------------------------
// Type: IMbnConnectionProfileEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnectionProfileEvents = *opaque{
    // TODO: Method 'OnProfileUpdate'
};
// --------------------------------------------------------
// Type: IMbnSmsConfiguration
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnSmsConfiguration = *opaque{
    // TODO: Method 'get_ServiceCenterAddress'
    // TODO: Method 'put_ServiceCenterAddress'
    // TODO: Method 'get_MaxMessageIndex'
    // TODO: Method 'get_CdmaShortMsgSize'
    // TODO: Method 'get_SmsFormat'
    // TODO: Method 'put_SmsFormat'
};
// --------------------------------------------------------
// Type: IMbnSmsReadMsgPdu
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnSmsReadMsgPdu = *opaque{
    // TODO: Method 'get_Index'
    // TODO: Method 'get_Status'
    // TODO: Method 'get_PduData'
    // TODO: Method 'get_Message'
};
// --------------------------------------------------------
// Type: IMbnSmsReadMsgTextCdma
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnSmsReadMsgTextCdma = *opaque{
    // TODO: Method 'get_Index'
    // TODO: Method 'get_Status'
    // TODO: Method 'get_Address'
    // TODO: Method 'get_Timestamp'
    // TODO: Method 'get_EncodingID'
    // TODO: Method 'get_LanguageID'
    // TODO: Method 'get_SizeInCharacters'
    // TODO: Method 'get_Message'
};
// --------------------------------------------------------
// Type: IMbnSms
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnSms = *opaque{
    // TODO: Method 'GetSmsConfiguration'
    // TODO: Method 'SetSmsConfiguration'
    // TODO: Method 'SmsSendPdu'
    // TODO: Method 'SmsSendCdma'
    // TODO: Method 'SmsSendCdmaPdu'
    // TODO: Method 'SmsRead'
    // TODO: Method 'SmsDelete'
    // TODO: Method 'GetSmsStatus'
};
// --------------------------------------------------------
// Type: IMbnSmsEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnSmsEvents = *opaque{
    // TODO: Method 'OnSmsConfigurationChange'
    // TODO: Method 'OnSetSmsConfigurationComplete'
    // TODO: Method 'OnSmsSendComplete'
    // TODO: Method 'OnSmsReadComplete'
    // TODO: Method 'OnSmsNewClass0Message'
    // TODO: Method 'OnSmsDeleteComplete'
    // TODO: Method 'OnSmsStatusChange'
};
// --------------------------------------------------------
// Type: IMbnServiceActivation
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnServiceActivation = *opaque{
    // TODO: Method 'Activate'
};
// --------------------------------------------------------
// Type: IMbnServiceActivationEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnServiceActivationEvents = *opaque{
    // TODO: Method 'OnActivationComplete'
};
// --------------------------------------------------------
// Type: IMbnVendorSpecificOperation
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnVendorSpecificOperation = *opaque{
    // TODO: Method 'SetVendorSpecific'
};
// --------------------------------------------------------
// Type: IMbnVendorSpecificEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnVendorSpecificEvents = *opaque{
    // TODO: Method 'OnEventNotification'
    // TODO: Method 'OnSetVendorSpecificComplete'
};
// --------------------------------------------------------
// Type: IMbnConnectionProfileManagerEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnConnectionProfileManagerEvents = *opaque{
    // TODO: Method 'OnConnectionProfileArrival'
    // TODO: Method 'OnConnectionProfileRemoval'
};
// --------------------------------------------------------
// Type: IMbnRadio
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnRadio = *opaque{
    // TODO: Method 'get_SoftwareRadioState'
    // TODO: Method 'get_HardwareRadioState'
    // TODO: Method 'SetSoftwareRadioState'
};
// --------------------------------------------------------
// Type: IMbnRadioEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnRadioEvents = *opaque{
    // TODO: Method 'OnRadioStateChange'
    // TODO: Method 'OnSetSoftwareRadioStateComplete'
};
// --------------------------------------------------------
// Type: IMbnMultiCarrier
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnMultiCarrier = *opaque{
    // TODO: Method 'SetHomeProvider'
    // TODO: Method 'GetPreferredProviders'
    // TODO: Method 'GetVisibleProviders'
    // TODO: Method 'GetSupportedCellularClasses'
    // TODO: Method 'GetCurrentCellularClass'
    // TODO: Method 'ScanNetwork'
};
// --------------------------------------------------------
// Type: IMbnMultiCarrierEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnMultiCarrierEvents = *opaque{
    // TODO: Method 'OnSetHomeProviderComplete'
    // TODO: Method 'OnCurrentCellularClassChange'
    // TODO: Method 'OnPreferredProvidersChange'
    // TODO: Method 'OnScanNetworkComplete'
    // TODO: Method 'OnInterfaceCapabilityChange'
};
// --------------------------------------------------------
// Type: IMbnDeviceServicesManager
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnDeviceServicesManager = *opaque{
    // TODO: Method 'GetDeviceServicesContext'
};
// --------------------------------------------------------
// Type: IMbnDeviceServicesContext
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnDeviceServicesContext = *opaque{
    // TODO: Method 'EnumerateDeviceServices'
    // TODO: Method 'GetDeviceService'
    // TODO: Method 'get_MaxCommandSize'
    // TODO: Method 'get_MaxDataSize'
};
// --------------------------------------------------------
// Type: IMbnDeviceServicesEvents
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnDeviceServicesEvents = *opaque{
    // TODO: Method 'OnQuerySupportedCommandsComplete'
    // TODO: Method 'OnOpenCommandSessionComplete'
    // TODO: Method 'OnCloseCommandSessionComplete'
    // TODO: Method 'OnSetCommandComplete'
    // TODO: Method 'OnQueryCommandComplete'
    // TODO: Method 'OnEventNotification'
    // TODO: Method 'OnOpenDataSessionComplete'
    // TODO: Method 'OnCloseDataSessionComplete'
    // TODO: Method 'OnWriteDataComplete'
    // TODO: Method 'OnReadData'
    // TODO: Method 'OnInterfaceStateChange'
};
// --------------------------------------------------------
// Type: IMbnDeviceService
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnDeviceService = *opaque{
    // TODO: Method 'QuerySupportedCommands'
    // TODO: Method 'OpenCommandSession'
    // TODO: Method 'CloseCommandSession'
    // TODO: Method 'SetCommand'
    // TODO: Method 'QueryCommand'
    // TODO: Method 'OpenDataSession'
    // TODO: Method 'CloseDataSession'
    // TODO: Method 'WriteData'
    // TODO: Method 'get_InterfaceID'
    // TODO: Method 'get_DeviceServiceID'
    // TODO: Method 'get_IsCommandSessionOpen'
    // TODO: Method 'get_IsDataSessionOpen'
};
// --------------------------------------------------------
// Type: IMbnPin
// TypeLayoutAttr: auto
// not generating the actual code for this type because its an abstract type (probably a COM type?)
pub const IMbnPin = *opaque{
    // TODO: Method 'get_PinType'
    // TODO: Method 'get_PinFormat'
    // TODO: Method 'get_PinLengthMin'
    // TODO: Method 'get_PinLengthMax'
    // TODO: Method 'get_PinMode'
    // TODO: Method 'Enable'
    // TODO: Method 'Disable'
    // TODO: Method 'Enter'
    // TODO: Method 'Change'
    // TODO: Method 'Unblock'
    // TODO: Method 'GetPinManager'
};

//
// functions
//

//
// Unicode Symbol Aliases
//
pub usingnamespace switch (@import("../zig.zig").unicode_mode) {
    .ansi => struct {
    },
    .wide => struct {
    },
    else => if (@import("builtin").is_test) struct {
    } else struct {
    },
};

//
// type imports
//
const BSTR = @import("automation.zig").BSTR;

test "" {
    const constant_export_count = 0;
    const type_export_count = 96;
    const func_count = 0;
    const unicode_alias_count = 0;
    const type_import_count = 1;
    @setEvalBranchQuota(0
        + constant_export_count
        + type_export_count
        + func_count
        + unicode_alias_count
        + type_import_count
        + 2 // TODO: why do I need these extra 2?
    );
    @import("std").testing.refAllDecls(@This());
}
